# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsSsoLogin < Formula
  desc "Interactive AWS SSO (Identity Center) login CLI"
  homepage "https://github.com/Photosynth-inc/aws-sso-login"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Photosynth-inc/aws-sso-login/releases/download/v0.1.0/aws-sso-login_Darwin_x86_64.tar.gz"
      sha256 "e8061fbaa07f0e6393e74d3e34614adb42d419cabdc83198efe3d4eeed419705"

      def install
        bin.install "aws-sso-login"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Photosynth-inc/aws-sso-login/releases/download/v0.1.0/aws-sso-login_Darwin_arm64.tar.gz"
      sha256 "18f0121c4d070ae4d950188b845542aa9db0408751fad13b311df0b41064057c"

      def install
        bin.install "aws-sso-login"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Photosynth-inc/aws-sso-login/releases/download/v0.1.0/aws-sso-login_Linux_x86_64.tar.gz"
      sha256 "fbf3ebcca664e2b262b529bd85ebb5e1d980c24ee3afa13900ecaf08f678b967"
      def install
        bin.install "aws-sso-login"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Photosynth-inc/aws-sso-login/releases/download/v0.1.0/aws-sso-login_Linux_arm64.tar.gz"
      sha256 "f3a64cd19b8a2b7bb92d6aea4042c0d72254af322a61b6eaf501e768be4f0388"
      def install
        bin.install "aws-sso-login"
      end
    end
  end
end
