# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsGoogleLogin < Formula
  desc ""
  homepage ""
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Photosynth-inc/aws-google-login/releases/download/v1.1.0/aws-google-login_Darwin_x86_64.tar.gz"
      sha256 "91261bad3ebe66e0e2fd18fee06b4ca171208e8aa9510ca6a9683a8b61ba1460"

      def install
        bin.install "aws-google-login"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Photosynth-inc/aws-google-login/releases/download/v1.1.0/aws-google-login_Darwin_arm64.tar.gz"
      sha256 "600906153cc729ed23f71efd5f5dd3199e89cd7fa1852a3b8bd7283dc883230a"

      def install
        bin.install "aws-google-login"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Photosynth-inc/aws-google-login/releases/download/v1.1.0/aws-google-login_Linux_x86_64.tar.gz"
      sha256 "1276b0bead0681324e24f00bb69650d4315821f0f7a8647d599e6ea3aa46fa81"
      def install
        bin.install "aws-google-login"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Photosynth-inc/aws-google-login/releases/download/v1.1.0/aws-google-login_Linux_arm64.tar.gz"
      sha256 "07fa9a49d2ba68371f35dc6492b651c47dc77f541642aebd2db144e13bc510dc"
      def install
        bin.install "aws-google-login"
      end
    end
  end
end
