# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsGoogleLogin < Formula
  desc ""
  homepage ""
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/Photosynth-inc/aws-google-login/releases/download/v1.0.0/aws-google-login_Darwin_x86_64.tar.gz"
      sha256 "c306b5af0d8766c40a2972d0731e1bff5280f2f8dfa614666910e3d93a88c36a"

      def install
        bin.install "aws-google-login"
      end
    end
    on_arm do
      url "https://github.com/Photosynth-inc/aws-google-login/releases/download/v1.0.0/aws-google-login_Darwin_arm64.tar.gz"
      sha256 "1e3df50a2f1974c6d3bd6b6b5098fc476c64ee0ce3ff6340035442de3fd0f3d5"

      def install
        bin.install "aws-google-login"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Photosynth-inc/aws-google-login/releases/download/v1.0.0/aws-google-login_Linux_x86_64.tar.gz"
        sha256 "ad1da7603d1eceabacf53e02973c6c8d14ae3e475849d2ed6d802a3dde6f16a0"

        def install
          bin.install "aws-google-login"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Photosynth-inc/aws-google-login/releases/download/v1.0.0/aws-google-login_Linux_arm64.tar.gz"
        sha256 "a270314f6aa1388d6a6621ba29301ae254a21c2b7430224497c3ead938417581"

        def install
          bin.install "aws-google-login"
        end
      end
    end
  end
end
